### PR TITLE
construct Bib and BibItem types for better I/O

### PR DESCRIPTION
**Pull request by stevengj**
This PR wraps the bibliography database in a `Bib` type that acts like `Associative{String,BibItem}`, and each item in a `BibItem{S}` type that acts like `Associative{String,String}`, where `S` is the item type (`:article`, `:book`, etcetera).

The main goal here is to allow nicer I/O.  Pretty-printing of the database, eventually special `show` methods to output to `text/bibtex` etcetera, and in the future `show` methods for `BibItem` that output the citation in a nice format.

The type of entry is now encoded in the `BibItem` type, similar to the entries in the bibTeX database, both to distinguish it from ordinary fields and to allow dispatch (e.g. a special show method for `BibItem{:article}`, `BibItem{:book}`, and so forth).

### CODE REVIEW

**Comment by stevengj** [comment]
For example, reading the `example.bib` file now looks like:
```
julia> bib = open(io -> Bib(io), "example/examples.bib", "r")
BibTeX.Bib with 92 entries:
  "coleridge"         => BibItem{:book}(16 entries)
  "wilde"             => BibItem{:book}(8 entries)
  "aristotle:physics" => BibItem{:book}(11 entries)
  "markey"            => BibItem{:online}(11 entries)
  "wassenberg"        => BibItem{:online}(11 entries)
  "baez/online"       => BibItem{:online}(9 entries)
  "moore:related"     => BibItem{:article}(12 entries)
  "almendro"          => BibItem{:patent}(7 entries)
  "sigfridsson"       => BibItem{:article}(13 entries)
  "malinowski"        => BibItem{:book}(11 entries)
  "nietzsche:ksa"     => BibItem{:book}(14 entries)
  "vangennep"         => BibItem{:book}(11 entries)
  "yoon"              => BibItem{:article}(8 entries)
  "gaonkar:in"        => BibItem{:incollection}(9 entries)
  "cms"               => BibItem{:manual}(14 entries)
  "moore"             => BibItem{:article}(9 entries)
  "laufenberg"        => BibItem{:patent}(10 entries)
  "iliad"             => BibItem{:book}(13 entries)
  "baez/article"      => BibItem{:article}(12 entries)
  "sorace"            => BibItem{:patent}(9 entries)
  "companion"         => BibItem{:book}(13 entries)
  "brandt"            => BibItem{:incollection}(16 entries)
  "set"               => BibItem{:set}(2 entries)
  "aksin"             => BibItem{:article}(8 entries)
  "glashow"           => BibItem{:article}(6 entries)
  "knuth:ct:related"  => BibItem{:book}(14 entries)
  "worman"            => BibItem{:book}(12 entries)
  "hyman"             => BibItem{:incollection}(16 entries)
  ⋮                   => ⋮

julia> bib["jaffe"]
BibTeX.BibItem{:collection} with 12 entries:
  "edition"     => "2"
  "shorttitle"  => "Regesta Pontificum Romanorum"
  "location"    => "Leipzig"
  "volumes"     => "2"
  "editoratype" => "redactor"
  "langid"      => "latin"
  "editor"      => "Jaff { \\'e } , Philipp"
  "editora"     => "Loewenfeld , Samuel and Kaltenbrunner , Ferdinand and Ewald…
  "date"        => "1885/1888"
  "annotation"  => "A \\texttt { collection } entry with \\texttt { edition } a…
  "indextitle"  => "Regesta Pontificum Romanorum"
  "title"       => "Regesta Pontificum Romanorum ab condita ecclesia ad annum p…
```

**Comment by stevengj** [comment]
I also fixed a bug where the field names were not being lowercased (they are supposed to be case-insensitive).

**Comment by bramtayl** [comment]
This looks great. This is the first substantive PR someone has made to one of my packages. My only comment is I have strong aversion to abbreviations, so I'd more inclined to go with Bibliography and BibliographyItem, or something more succinct like WorksCited and Work

**Comment by bramtayl** [comment]
Also I'm confused why coverage went down

**Comment by stevengj** [comment]
Okay, I'll expand it to `Bibliography` and `Citation`, maybe?  `Work` is a bit vague.

Coverage went down because I added a bunch of new methods that weren't exercised by the tests; I'm adding tests now.

**Comment by bramtayl** [comment]
Yay!

**Pull request merged**
