### PR TITLE
WIP: latex substitutions

### PR DESCRIPTION
**Pull request by stevengj**
This is a WIP to replace a small subset of common LaTeX directives with Unicode and/or Markdown, e.g. to transform `foo \emph{bar} {\bf baz} {\^{u}}` to `foo _bar_ **baz** û`.

It's not correct for nested directives yet, or for equations (where it would be nice to at least substitute greek letters and sub/superscripts, since both commonly occur in scientific article titles).  

Right now, it's using a Regex to match LaTeX directives, but I think it actually needs to have a custom parser so that it can correctly match braces `{...}`.  (Fortunately such a parser is pretty easy to write.)

### CODE REVIEW

**Comment by bramtayl** [comment]
I had also started very briefly something on this:

```
tex_to_markdown(tex) = begin
    tokens = matchall(r"[^\s\n\\{}]+|\\|{|}", tex)
    results = String[]
    while !isempty(tokens)
        token = shift!(tokens)
        if token == "\\"
            function_name = shift!(tokens)
            token = shift!(tokens)
            if token == "{"
                function_args = String[]
                token = shift!(tokens)
                while token != "}"
                    push!(function_args, token)
                    token = shift!(tokens)
                end
            end
            function_arg = join(function_args, " ")
            push!(results, string_macro(function_name, function_arg))
        else
            push!(results, token)
        end
    end
    join(results, " ")
end

string_macro(function_name, function_arg = "") = 
    if function_name == "texttt"
        string("`", function_arg, "`")
    else
        error("Cannot recognize string macro $function_name")
    end
```

**Comment by bramtayl** [comment]
I'm confused about how LaTeX is working here. Is this bracket notation denoting something like function names and function arguments? In the examples file there are things like `{\"O}`. Is it the case that `"` is like a function and O is like an argument? But then in a case like `{\bf}` is not calling b on f.

**Comment by stevengj** [comment]
@bramtayl, the function name after the `\` can be either a string of alphabetic character or a single non-alphabetic character.

**Comment by stevengj** [comment]
Okay, I've swapped in a custom parser that handles nested directives etcetera, with some rudimentary equation support (at least greek letters and sub/superscripts … article titles rarely contain complex equations).

**Comment by stevengj** [comment]
Hmm, found a bug, not ready to merge yet...

**Comment by bramtayl** [comment]
This looks really great. I had also been working on something but since this is tested/working I'd be inclined just to go with this.

**Comment by bramtayl** [comment]
Let me know when this is good to go and I'll merge it

**Comment by bramtayl** [comment]
In case you're curious, what I have currently looks like this:

```julia
string_macro(function_name, function_arg = "") =
    if function_name == "texttt"
        string("`", function_arg, "`")
    elseif function_name == '^'
        string(function_arg, "\u0302")
    else
        error("Cannot recognize string macro $function_name")
    end

get_token_and_deTeX!(parser) = begin
    token = next_token_default!(parser)
    if token == "\\"
        function_name = get_token_and_deTeX!(parser)
        if isalpha(function_name[1])
            function_args = eltype(Parser)[]
            token = get_token_and_deTeX!(parser)
            while all(isspace, token)
                token = get_token_and_deTeX!(parser)
            end
            if token == "{"
                token = get_token_and_deTeX!(parser)
                while token != "}"
                    push!(function_args, token)
                    token = get_token_and_deTeX!(parser)
                end
                function_arg = join(function_args)
                string_macro(function_name, function_arg)
            else
                while token != "}"
                    push!(function_args, token)
                    token = get_token_and_deTeX!(parser)
                end
                function_arg = join(function_args)
                string(string_macro(function_name, function_arg), "}")
            end
        else
            character_function = function_name[1]
            function_arg = function_name[2:end]
            string_macro(character_function, function_arg)
        end
    else
        token
    end
end

tex_to_markdown(tex) = begin
    parser = Parser(matchall(r"[^\\\s{}]+|\\|\s|{|}", tex))
    results = String[]
    while !isempty(parser)
        push!(results, get_token_and_deTeX!(parser))
    end
    join(results)
end

tex_to_markdown("\\texttt{bold words} {\\texttt bold words} {\\^o}")
```

**Comment by bramtayl** [comment]
Upon further reflection, this might belong in a separate package, maybe LaTeXConversions.jl?

**Comment by stevengj** [comment]
I don't think this is generally useful outside of processing bibTeX bibliographies, because this supports only a minuscule portion of LaTeX.  This is fine for a bibliography, because generally citations use at most a tiny bit of formatting (e.g. extremely simple equations, mainly for superscripts and greek letters), but I don't think it would be very useful in other contexts.

**Comment by bramtayl** [comment]
Ok, well, maybe someday...

**Pull request merged**
